#!/usr/bin/env bash
set -euo pipefail

# Defluff first-run installer. Idempotent: every step is a no-op when already
# satisfied, so it is safe to re-run. It installs the native prerequisites
# (Homebrew, Python 3.12, Postgres, ffmpeg, Ollama), provisions the runtime
# under ~/Library/Application Support/Defluff, sets up the database, pulls the
# model, and registers the backend LaunchAgent so everything starts on its own
# at login. Runs the same whether launched from the git checkout (scripts/) or
# from inside Defluff.app (Contents/Resources/).

log()  { printf '\n\033[1m==> %s\033[0m\n' "$*"; }
info() { printf '    %s\n' "$*"; }
warn() { printf '\033[33m    ! %s\033[0m\n' "$*" >&2; }

# --- Resolve source (where the bundled backend + sibling scripts live) --------
SRC_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
if [[ -d "$SRC_DIR/backend" ]]; then
    SRC_ROOT="$SRC_DIR"                       # inside Defluff.app/Contents/Resources
else
    SRC_ROOT="$(cd "$SRC_DIR/.." && pwd)"     # git checkout (scripts/..)
fi
SRC_BACKEND="$SRC_ROOT/backend"
SRC_SCRIPTS="$SRC_DIR"

# --- Resolve runtime target ---------------------------------------------------
DEFLUFF_HOME="${DEFLUFF_HOME:-$HOME/Library/Application Support/Defluff}"
export DEFLUFF_HOME
HF_HOME_DIR="$DEFLUFF_HOME/.cache/huggingface"
OLLAMA_MODEL="${OLLAMA_MODEL:-gemma4:26b}"
OLLAMA_URL="${OLLAMA_HOST:-http://127.0.0.1:11434}"
BACKEND_URL="http://127.0.0.1:8000"

wait_for() {
    local name="$1" url="$2" attempts="${3:-60}"
    for _ in $(seq 1 "$attempts"); do
        if curl -fsS "$url" >/dev/null 2>&1; then
            info "$name is ready."
            return 0
        fi
        sleep 1
    done
    warn "$name did not become ready at $url"
    return 1
}

# --- 1. Homebrew --------------------------------------------------------------
log "Checking Homebrew"
if [[ -x /opt/homebrew/bin/brew ]]; then
    BREW=/opt/homebrew/bin/brew
elif [[ -x /usr/local/bin/brew ]]; then
    BREW=/usr/local/bin/brew
else
    info "Installing Homebrew (you may be prompted for your password)..."
    /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
    BREW="$([[ -x /opt/homebrew/bin/brew ]] && echo /opt/homebrew/bin/brew || echo /usr/local/bin/brew)"
fi
eval "$("$BREW" shellenv)"
info "Using Homebrew at $BREW"

# --- 2. Native packages -------------------------------------------------------
log "Installing native dependencies"
ensure_formula() { brew list --versions "$1" >/dev/null 2>&1 || brew install "$1"; }
ensure_formula python@3.12
ensure_formula postgresql@15
ensure_formula ffmpeg
if [[ ! -d /Applications/Ollama.app ]] && ! command -v ollama >/dev/null 2>&1; then
    info "Installing Ollama..."
    brew install --cask ollama
else
    info "Ollama already present."
fi

PY="$("$BREW" --prefix python@3.12)/bin/python3.12"
PG_BIN="$("$BREW" --prefix postgresql@15)/bin"
export PATH="$PG_BIN:$PATH"

# --- 3. Start Postgres --------------------------------------------------------
log "Starting Postgres"
brew services start postgresql@15 >/dev/null 2>&1 || brew services start postgresql@15
for _ in $(seq 1 60); do
    if "$PG_BIN/pg_isready" -h 127.0.0.1 -p 5432 >/dev/null 2>&1; then break; fi
    sleep 1
done
"$PG_BIN/pg_isready" -h 127.0.0.1 -p 5432 >/dev/null 2>&1 \
    && info "Postgres is accepting connections." \
    || warn "Postgres is not responding yet; database setup may fail."

# --- 4. Start Ollama ----------------------------------------------------------
log "Starting Ollama"
if ! curl -fsS "$OLLAMA_URL/api/tags" >/dev/null 2>&1; then
    if [[ -d /Applications/Ollama.app ]]; then
        open -a Ollama
    else
        nohup ollama serve >/dev/null 2>&1 &
    fi
fi
wait_for "Ollama" "$OLLAMA_URL/api/tags" 60 || true

# --- 5. Provision the runtime -------------------------------------------------
log "Provisioning runtime at $DEFLUFF_HOME"
mkdir -p "$DEFLUFF_HOME/scripts" "$DEFLUFF_HOME/.logs" "$HF_HOME_DIR"

if [[ "$SRC_BACKEND" -ef "$DEFLUFF_HOME/backend" ]]; then
    info "Backend source is the install target; skipping copy."
else
    rsync -a --delete \
        --exclude '.venv' --exclude '__pycache__' --exclude '*.egg-info' \
        --exclude '.pytest_cache' --exclude '.ruff_cache' \
        "$SRC_BACKEND/" "$DEFLUFF_HOME/backend/"
fi

for s in run-backend.sh start-backend-service.sh stop-backend-service.sh \
         setup-local-db.sh bootstrap.sh uninstall.sh; do
    [[ -f "$SRC_SCRIPTS/$s" ]] && cp "$SRC_SCRIPTS/$s" "$DEFLUFF_HOME/scripts/$s"
done
chmod +x "$DEFLUFF_HOME/scripts/"*.sh

# --- 6. .env (do not clobber an existing one) ---------------------------------
if [[ ! -f "$DEFLUFF_HOME/.env" ]]; then
    log "Writing default config ($DEFLUFF_HOME/.env)"
    cat > "$DEFLUFF_HOME/.env" <<ENV
# Defluff runtime config (generated by bootstrap.sh). Edit, then restart with
# scripts/start-backend-service.sh to apply.
DATABASE_URL=postgresql://defluff:defluff@127.0.0.1:5432/defluff
OLLAMA_HOST=$OLLAMA_URL
OLLAMA_MODEL=$OLLAMA_MODEL
# "-1" keeps the model resident for instant responses; "0" unloads after each
# request to reclaim RAM; "5m" is Ollama's default.
OLLAMA_KEEP_ALIVE=-1
SEARCH_PROVIDER=duckduckgo
GOOGLE_SEARCH_API_KEY=
GOOGLE_SEARCH_ENGINE_ID=
WHISPER_MODEL=small
WHISPER_DEVICE=auto
WHISPER_COMPUTE_TYPE=default
# YouTube anti-bot (yt-dlp): point at a cookies.txt to authenticate. Blank = off.
YOUTUBE_COOKIES_FROM_BROWSER=
YOUTUBE_COOKIE_FILE=
ENV
else
    info "Keeping existing $DEFLUFF_HOME/.env"
fi

# --- 7. Python venv -----------------------------------------------------------
log "Setting up the Python backend"
if [[ ! -x "$DEFLUFF_HOME/backend/.venv/bin/uvicorn" ]]; then
    "$PY" -m venv "$DEFLUFF_HOME/backend/.venv"
    "$DEFLUFF_HOME/backend/.venv/bin/python" -m pip install --upgrade pip >/dev/null
    "$DEFLUFF_HOME/backend/.venv/bin/python" -m pip install -e "$DEFLUFF_HOME/backend"
else
    info "Backend venv already present."
fi

# --- 8. Database --------------------------------------------------------------
log "Setting up the database"
"$DEFLUFF_HOME/scripts/setup-local-db.sh"

# --- 9. Model -----------------------------------------------------------------
log "Pulling the Ollama model ($OLLAMA_MODEL)"
if ollama list 2>/dev/null | awk '{print $1}' | grep -qx "$OLLAMA_MODEL"; then
    info "Model already present."
elif ! ollama pull "$OLLAMA_MODEL"; then
    warn "Could not pull $OLLAMA_MODEL. Pull or import it manually, then restart Defluff."
fi

# --- 10. Backend service ------------------------------------------------------
log "Registering the backend service (starts at login, auto-restarts)"
"$DEFLUFF_HOME/scripts/start-backend-service.sh"

# --- 11. Done -----------------------------------------------------------------
if wait_for "Defluff backend" "$BACKEND_URL/health" 90; then
    touch "$DEFLUFF_HOME/.installed"
    log "Defluff is ready. You can open the app now."
else
    warn "Backend not healthy yet. Check logs: $DEFLUFF_HOME/.logs/backend.err.log"
    exit 1
fi
